# Generated by Django 5.1.6 on 2025-02-22 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article_upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
                ('journal', models.CharField(max_length=255)),
                ('article_link', models.URLField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article_upload.article')),
            ],
        ),
    ]
